name: Redesics_env
dependencies:
  - python=3.9
  - pip=21.2.4
  - pip:
    - numpy==1.20.3
    - pandas==1.2.0
    - scikit-misc==0.1.4
    - scikit-learn==1.0.2
    - scanpy==1.9.3
    - Shapely==1.8.5
    - alphashape==1.3.1

